### PR TITLE
Added ItemStack config parsing in the starter-pack

### PR DESCRIPTION
**Pull request by justWerns**

### CODE REVIEW

**Comment by justWerns** [comment]
Tested the code out, but I'd like to test it out on the dev server before deploying. I want to make sure there's no wonky behavior because of the way I used the copy constructor.

I'm also not sure how we want to update the configuration, since the default has already been saved, so the changes to config.yml won't be written.

In a similar vein, any changes to the Byte$ object in minecraft__byte-economy will need to be mirrored in this config. I think there's already discussion about a central place for shared code, and that would be super beneficial here.

**Comment by Zorro909** [comment]
This might very well work, however I would suggest making one Config Object, instead of it being possible via three ways.
So for example an Item would be structured like this:
itemKey:
  material: BIRCH_LOG
  amount: 2
  displayName: "Override Name"
  lore:
   \- "First Line"
   \- "Second Line"
etc.

In this you can omit entries like lore or displayName, but most important is that it makes the code and the config easier to read and modify. (Only one way to read it from the Config)

And about a central Code dependency (or library or however you wanna call it), I might be contacting @pyxld-kris again, about what should be included and start working on that soon.

**Comment by justWerns** [comment]
Aight, no one was supposed to notice how lazy it was to keep the separate formats 😅 but you're completely correct. Having one way for items to be defined is probably better, and it's way cleaner from a code perspective. The only arguments I would have for the use of two formats like this, and they're very similar/related arguments, would be ease of readability to people who aren't used to the [yaml schema for items](https://www.spigotmc.org/wiki/itemstack-serialization/) (finding that took me an embarrassingly long time) and simply as a shortcut for configuration. That said, I'm not sure what the bare minimum ItemStack schema looks like, so it might not even be much of a shortcut. Just something I'll need to play around with.

But unless anyone has objections/strong opinions about getting rid of the "shortcut" format for vanilla items, I'll switch them over to the full ItemStack config and remove the logic.

**Comment by justWerns** [comment]
Switched code and config around to only use a single config format. Assuming no one has any more ideas for improvements, we'll get this tested with multiple people on the dev server and hopefully get this merge for production!

**Comment by pyxld-kris** [comment]
Awesome! Thank you Werns :D I think this is ready to merge, but before we do that could you give me some steps we'll need to take in order to test this? I imagine well need to delete user data from the server unless there's a simpler way.

Once we have that, we can merge this and get everything on the dev server!

**Comment by Zorro909** [comment]
Testing would only need to include "new" Players (either blank server or deleting player data) joining a Server and testing if they get the correct Items and afterwards checking that if they disconnect and then rejoin the Server they don't get the Items again.

**Comment by pyxld-kris** [comment]
Perfect, merging now. We're currently moving our backend stuff over to the Azure cloud (due to a grant we got :D), which includes our dev server. I'll let you guys know in Discord when that's up and we can test things!

**Pull request merged**
